Archive xml configuration used in each test
jboss-eap-qe/vdx-wildfly-testsuite pull request #13
Opened 2017-01-12 11:38 UTC by mnovak1

2017-01-12 11:39 UTC, mnovak1 commented
Pls for review.

2017-01-12 15:49 UTC, rsvoboda requested changes

2017-01-12 15:49 UTC, rsvoboda commented on src/test/java/org/wildfly/test/integration/vdx/TestBase.java
> +    private static Path testArchiveDirectory;
Why this rename ?

Why so many changes / reordering ?

2017-01-12 15:49 UTC, rsvoboda commented on src/test/java/org/wildfly/test/integration/vdx/TestBase.java
> -        testDirectory = Paths.get("target", "server-logs", this.getClass().getSimpleName(), testName.getMethodName());
Why test-output instead of server-logs ?

2017-01-12 15:49 UTC, rsvoboda commented on src/test/java/org/wildfly/test/integration/vdx/utils/server/ServerDomain.java
> +    public void archiveModifiedUsedConfig() throws Exception {
Why this is not in ServerBase ?

Version for standalone seems the same.

2017-01-12 15:49 UTC, rsvoboda commented on src/test/java/org/wildfly/test/integration/vdx/utils/server/ServerDomain.java
> +            Files.createDirectories(TestBase.getTestArchiveDirectory());
It would be better if TestBase ensures it's created

2017-01-13 09:01 UTC, mnovak reviewed
I did some changes and re-pushed. I did not like to have cycle dependency between test and server so I added setTestArchive() method to Server interface. 
Test archive directory will be created in setUp() method and removed further checks for its existence.

2017-01-13 09:01 UTC, mnovak commented on src/test/java/org/wildfly/test/integration/vdx/TestBase.java
> +    private static Path testArchiveDirectory;
testArchiveDirectory is private static and is recommended to have it before non-static variables so it's not a such mess. "testDirectory" did not reflect for what this variable is used.

2017-01-13 09:01 UTC, mnovak commented on src/test/java/org/wildfly/test/integration/vdx/TestBase.java
> -        testDirectory = Paths.get("target", "server-logs", this.getClass().getSimpleName(), testName.getMethodName());
There is a change that from now this directory does not contains just server-logs but also xml configuration used in the test. "server-logs" would be confusing. "test-output" better reflects current content. I have no problem to change to something better :-)

2017-01-13 09:01 UTC, mnovak commented on src/test/java/org/wildfly/test/integration/vdx/utils/server/ServerDomain.java
> +    public void archiveModifiedUsedConfig() throws Exception {
There is different location of xml config for standalone and domain. I try to avoid "if ... then ..." when possible but in this case you're right there is too much of the same code. I'll change it.

2017-01-13 09:01 UTC, mnovak commented on src/test/java/org/wildfly/test/integration/vdx/utils/server/ServerDomain.java
> +            Files.createDirectories(TestBase.getTestArchiveDirectory());
Where do you suggest to place it?

2017-01-13 13:18 UTC, rsvoboda approved these changes

2017-01-13 13:18 UTC, merged